// <auto-generated />
using System;
using HPlusSports.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HPlusSports.DAL.Migrations
{
    [DbContext(typeof(HPlusSportsSqliteContext))]
    [Migration("20200812211025_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("HPlusSports.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zipcode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("HPlusSports.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnName("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalespersonId")
                        .HasColumnName("SalespersonID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'none'");

                    b.Property<decimal?>("TotalDue")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderDate")
                        .HasName("IX_Order");

                    b.HasIndex("SalespersonId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("HPlusSports.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnName("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnName("ProductID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("HPlusSports.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Perishable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnName("ProductCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("ProductName")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Variety")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasDiscriminator<bool>("Perishable").HasValue(false);
                });

            modelBuilder.Entity("HPlusSports.Models.SalesGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("State", "Type")
                        .IsUnique()
                        .HasName("IX_StateType");

                    b.ToTable("SalesGroup");
                });

            modelBuilder.Entity("HPlusSports.Models.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SalespersonID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SalesGroupState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasMaxLength(2)
                        .HasDefaultValue("CA");

                    b.Property<int>("SalesGroupType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("State")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SalesGroupState", "SalesGroupType");

                    b.ToTable("Salesperson");
                });

            modelBuilder.Entity("HPlusSports.Models.PerishableProduct", b =>
                {
                    b.HasBaseType("HPlusSports.Models.Product");

                    b.Property<int?>("ExpirationDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Refrigerated")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(true);
                });

            modelBuilder.Entity("HPlusSports.Models.Order", b =>
                {
                    b.HasOne("HPlusSports.Models.Customer", "Customer")
                        .WithMany("Order")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Order_Customer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HPlusSports.Models.Salesperson", "Salesperson")
                        .WithMany("Order")
                        .HasForeignKey("SalespersonId")
                        .HasConstraintName("FK_Order_Salesperson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HPlusSports.Models.OrderItem", b =>
                {
                    b.HasOne("HPlusSports.Models.Order", "Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderItem_Order")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HPlusSports.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_OrderItem_Product1")
                        .HasPrincipalKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HPlusSports.Models.Salesperson", b =>
                {
                    b.HasOne("HPlusSports.Models.SalesGroup", "SalesGroup")
                        .WithMany("Salespeople")
                        .HasForeignKey("SalesGroupState", "SalesGroupType")
                        .HasPrincipalKey("State", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
